[font]
normal.family = "Fira Code"
normal.style = "Regular"
size = 14.0

[window]
padding.x = 10
padding.y = 10
decorations = "None"  # Matches Kitty's hide_window_decorations=yes
opacity = 0.98        # Matches Kitty's background_opacity

[cursor]
style.shape = "Underline"  # Matches Kitty's cursor_shape=underline
style.blinking = "Off"    # Matches Kitty's disable_ligatures=cursor (no cursor ligature effects)
vi_mode_style = "Underline"

[scrolling]
history = 2000  # Matches Kitty's scrollback_lines

[colors.primary]
background = "#1a1b26"  # Matches Kitty's background
foreground = "#a9b1d6"  # Matches Kitty's foreground

[colors.normal]
black = "#32344a"   # Matches Kitty's color0
red = "#f7768e"     # Matches Kitty's color1
green = "#9ece6a"   # Matches Kitty's color2
yellow = "#e0af68"  # Matches Kitty's color3
blue = "#7aa2f7"    # Matches Kitty's color4
magenta = "#ad8ee6" # Matches Kitty's color5
cyan = "#449dab"    # Matches Kitty's color6
white = "#787c99"   # Matches Kitty's color7

[colors.bright]
black = "#444b6a"   # Matches Kitty's color8
red = "#ff7a93"     # Matches Kitty's color9
green = "#b9f27c"   # Matches Kitty's color10
yellow = "#ff9e64"  # Matches Kitty's color11
blue = "#7da6ff"    # Matches Kitty's color12
magenta = "#bb9af7" # Matches Kitty's color13
cyan = "#0db9d7"    # Matches Kitty's color14
white = "#acb0d0"   # Matches Kitty's color15

[colors.selection]
background = "#7aa2f7"  # Matches Kitty's selection_background
foreground = "#1a1b26"  # Matches Kitty's selection_foreground

[keyboard]
bindings = [
  { key = "C", mods = "Super", action = "Copy" },
  { key = "V", mods = "Super", action = "Paste" },
  { key = "F11", action = "ToggleFullscreen" },
]


[terminal.shell]
program = "zsh"
args = ["-l", "-c", "tmux new -As alacritty"]                                                                                #
