#!/bin/bash

export DOTFILES_DIR="${HOME}/.dotfiles"
export MACHINE_CORES=$(echo "$(nproc) - 1" | bc)
# n-1: http://archlever.blogspot.com/2013/09/lies-damned-lies-and-truths-backed-by.html

# user-specific data locations
export XDG_DATA_HOME="${HOME}/.local/share"  # data files (submodules)
export XDG_CONFIG_HOME="${HOME}/.config"     # configuration files (also set in LaunchAgent)
export XDG_STATE_HOME="${HOME}/.local/state" # state files (logs, history, recently used files, current app state, etc)
export XDG_CACHE_HOME="${HOME}/.cache"       # ephemeral data files

# DO NOT SET: XDG_RUNTIME_DIR="${HOME}/.sockets" # ephemeral runtime files (sockets, named pipes, etc)
export XDG_LOCALS_DIR="${DOTFILES_DIR}/locals"   # un-synced, un-tracked dotfiles (not spec)
export XDG_SECURE_DIR="${DOTFILES_DIR}/secure"   # synced, tracked sensitive dotfiles (not spec)

# Zsh
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

# Homebrew
export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"

# FZF
export FZF_DEFAULT_COMMAND="fdfind --hidden --type f --exclude .git --exclude node_modules"
export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
export FZF_DEFAULT_OPTS="
  --no-multi
  --exact
  --tiebreak=index
  --color='bg:#1d1e20,bg+:#1d1e20,preview-bg:#1d1e20,border:#1d1e20'
  --bind='ctrl-f:preview-down'
  --bind='ctrl-b:preview-up'
"

# Mise
export MISE_DIR="${XDG_DATA_HOME}/mise"
export MISE_JOBS="${MACHINE_CORES}"
export MISE_RUBY_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/mise/default-libraries-ruby"
export MISE_GO_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/mise/default-libraries-golang"
export MISE_NODE_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/mise/default-libraries-nodejs"
export MISE_PERL_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/mise/default-libraries-perl"
export MISE_PYTHON_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/mise/default-libraries-python"

# extra config options for installs
export POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-uuid=e2fs --with-libxml"
export REDIS_EXTRA_CONFIGURE_OPTIONS="BUILD_TLS=yes"

export ORG_HOME="${HOME}/Org"
export GRIND_DATA_DIR="${XDG_SECURE_DIR}/state/grind"

# --------- PATH --------
[[ -z "${DOTFILES_DIR}" ]]    && echo "WARNING: DOTFILES_DIR is not set in ${0}"
[[ -z "${XDG_DATA_HOME}" ]]   && echo "WARNING: XDG_DATA_HOME is not set in ${0}"
[[ -z "${HOMEBREW_PREFIX}" ]] && echo "WARNING: HOMEBREW_PREFIX is not set in ${0}"

PATH=":${XDG_LOCALS_DIR}/bin"
PATH+=":${XDG_SECURE_DIR}/bin"
PATH+=":${DOTFILES_DIR}/bin"
PATH+=":${XDG_DATA_HOME}/mise/shims"
PATH+=":${HOMEBREW_PREFIX}/bin"
PATH+=":${HOMEBREW_PREFIX}/sbin"
PATH+=":${XDG_CONFIG_HOME}/emacs/bin"
PATH+=":${HOME}/.local/bin"
PATH+=":/usr/local/sbin"
PATH+=":/usr/local/bin"
PATH+=":/usr/sbin"
PATH+=":/usr/bin"
PATH+=":/sbin"
PATH+=":/bin"
PATH+=":/usr/games"
PATH+=":/usr/local/games"
PATH+=":/snap/bin"
export PATH
