#!/bin/bash

export DOTFILES_DIR="${HOME}/.dotfiles"
export MACHINE="linux"  # uname -s
export MACHINE_CORES=11 # $(echo "$(nproc) - 1" | bc)
# n-1: http://archlever.blogspot.com/2013/09/lies-damned-lies-and-truths-backed-by.html

# user-specific data locations
export XDG_DATA_HOME="${HOME}/.local/share"  # data files (submodules)
export XDG_CONFIG_HOME="${HOME}/.config"     # configuration files (also set in LaunchAgent)
export XDG_STATE_HOME="${HOME}/.local/state" # state files (logs, history, recently used files, current app state, etc)
export XDG_CACHE_HOME="${HOME}/.cache"       # ephemeral data files

# DO NOT SET: XDG_RUNTIME_DIR="${HOME}/.sockets" # ephemeral runtime files (sockets, named pipes, etc)
export XDG_LOCALS_DIR="${DOTFILES_DIR}/locals"   # un-synced, un-tracked dotfiles (not spec)
export XDG_SECURE_DIR="${DOTFILES_DIR}/secure"   # synced, tracked sensitive dotfiles (not spec)

# ---------
export AWS_CONFIG_FILE="${XDG_SECURE_DIR}/config/aws/config"
export AWS_SHARED_CREDENTIALS_FILE="${XDG_SECURE_DIR}/config/aws/credentials"
export BUNDLE_DEFAULT_INSTALL_USES_PATH="${XDG_CACHE_HOME}/bundler"
export BUNDLE_USER_CACHE="${XDG_CACHE_HOME}/bundler"
export CARGO_HOME="${XDG_DATA_HOME}/rust/cargo"
export CUDA_CACHE_PATH="${XDG_CACHE_HOME}/nv"
export CUPS_CACHEDIR="${XDG_CONFIG_HOME}/cups"
export CURLOPT_NETRC_FILE="${XDG_SECURE_DIR}/config/netrc"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export DOOMDIR="${XDG_CONFIG_HOME}/doom"
export DOTNET_CLI_HOME="${XDG_DATA_HOME}/dotnet"
export GEMRC="${XDG_CONFIG_HOME}/gem/gemrc"
export GEM_SPEC_CACHE="${XDG_CACHE_HOME}/gem"
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export GOPATH="${XDG_DATA_HOME}/go"
export GRIND_DATA_DIR="${XDG_SECURE_DIR}/state/grind"
export GRIPHOME="${XDG_CONFIG_HOME}/grip"
export GTAGSCONF="${XDG_CONFIG_HOME}/gtags/gtags.conf"
export HEX_HOME="${XDG_STATE_HOME}/hex"
export INPUTRC="${XDG_CONFIG_HOME}/inputrc"
export IPYTHONDIR="${XDG_DATA_HOME}/ipython"
export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}/jupyter"
export LESSHISTFILE="${XDG_DATA_HOME}/less/history"
export LESSKEY="${XDG_CONFIG_HOME}/less/keys"
export NODE_REPL_HISTORY="${XDG_STATE_HOME}/node/repl_history"
export NPM_CONFIG_CACHE="${XDG_CACHE_HOME}/npm"
export NPM_CONFIG_DEVDIR="${XDG_CACHE_HOME}/npm/gyp"
export NPM_CONFIG_PREFIX="${XDG_DATA_HOME}/npm"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"
export PERL_CPANM_HOME="${XDG_CACHE_HOME}/cpanm"
export PSQLRC="${XDG_CONFIG_HOME}/psql/psqlrc"
export PYENV_ROOT="${XDG_DATA_HOME}/pyenv"
export REDISCLI_HISTFILE="${XDG_STATE_HOME}/redis/rediscli_history"
export RUBY_DEBUG_HISTORY_FILE="${XDG_STATE_HOME}/rdbg_history"
export RUSTUP_HOME="${XDG_DATA_HOME}/rust/rustup"
export SOLARGRAPH_CACHE="${XDG_CACHE_HOME}/solargraph"
export TLDR_CACHE_DIR="${XDG_CACHE_HOME}/tldr"
export VIMINIT="source $XDG_CONFIG_HOME/vim/vimrc"
export WGETRC="${XDG_CONFIG_HOME}/wget/wgetrc"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
export ZELLIJ_CONFIG_DIR="${XDG_CONFIG_HOME}/zellij"
# ---------

# Zsh
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

# Homebrew
export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"

# FZF
export FZF_DEFAULT_COMMAND="fdfind --hidden --type f --exclude .git --exclude node_modules"
export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
export FZF_DEFAULT_OPTS="
  --no-multi
  --exact
  --tiebreak=index
  --color='bg:#1d1e20,bg+:#1d1e20,preview-bg:#1d1e20,border:#1d1e20'
  --bind='ctrl-f:preview-down'
  --bind='ctrl-b:preview-up'
"

# Mise
export MISE_DIR="${XDG_DATA_HOME}/mise"
export MISE_JOBS="${MACHINE_CORES}"
export MISE_RUBY_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/mise/default-libraries-ruby"
export MISE_GO_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/mise/default-libraries-golang"
export MISE_NODE_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/mise/default-libraries-nodejs"
export MISE_PERL_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/mise/default-libraries-perl"
export MISE_PYTHON_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/mise/default-libraries-python"

# extra config options for installs
export POSTGRES_EXTRA_CONFIGURE_OPTIONS="--with-uuid=e2fs --with-libxml"
export REDIS_EXTRA_CONFIGURE_OPTIONS="BUILD_TLS=yes"

export ORG_HOME="${HOME}/Org"

# --------- PATH --------
[[ -z "${DOTFILES_DIR}" ]]    && echo "WARNING: DOTFILES_DIR is not set in ${0}"
[[ -z "${XDG_DATA_HOME}" ]]   && echo "WARNING: XDG_DATA_HOME is not set in ${0}"
[[ -z "${HOMEBREW_PREFIX}" ]] && echo "WARNING: HOMEBREW_PREFIX is not set in ${0}"

PATH=":${XDG_LOCALS_DIR}/bin"
PATH+=":${XDG_SECURE_DIR}/bin"
PATH+=":${DOTFILES_DIR}/bin"
PATH+=":${XDG_DATA_HOME}/mise/shims"
PATH+=":${HOMEBREW_PREFIX}/bin"
PATH+=":${HOMEBREW_PREFIX}/sbin"
PATH+=":${XDG_CONFIG_HOME}/emacs/bin"
PATH+=":${HOME}/.local/bin"
PATH+=":/usr/local/cuda-12.6/bin"
PATH+=":/usr/local/sbin"
PATH+=":/usr/local/bin"
PATH+=":/usr/sbin"
PATH+=":/usr/bin"
PATH+=":/sbin"
PATH+=":/bin"
PATH+=":/usr/games"
PATH+=":/usr/local/games"
PATH+=":/snap/bin"
export PATH

export LD_LIBRARY_PATH="/usr/local/cuda-12.6/lib64:${LD_LIBRARY_PATH}"
